DROP TABLE IF EXISTS "produits";

CREATE TABLE IF NOT EXISTS "produits" (
  "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT,
  "description" TEXT,
  "reference" INTEGER NOT NULL,
  "origine" TEXT,
  "price" REAL NOT NULL,
  "type" TEXT,
  "disponibilite" TEXT
);

SET client_encoding TO 'UTF8';

INSERT INTO "produits"("id","name", "description", "reference", "origine", "price", "type", "disponibilite") VALUES
(1,'Expresso', 'Café fort et concentré préparé en faisant passer de l''eau chaude à travers du café finement moulu.',100955890, 'Italie', 20.99,'Corsé', 'Oui'),
(2,'Columbian', 'Café moyennement corsé avec une acidité vive et une saveur riche.',100955894, 'Colombie', 18.75,'Acide', 'Oui'),
(3,'Ethiopian Yirgacheffe', 'Réputé pour son arôme floral, son acidité vive et ses notes de saveur citronnée.',105589090, 'Ethiopie', 22.50,'Fruité', 'Oui'),
(4,'Brazilian Santos', 'Café doux et lisse avec un profil de saveur de noisette.', 134009550, 'Brésil', 17.80,'Doux', 'Oui'),
(5,'Guatemalan Antigua', 'Café corsé avec des nuances chocolatées et une pointe d''épice.',256505890, 'Guatemala', 21.25,'Corsé', 'Oui'),
(6,'Kenyan AA', 'Café complexe connu pour son acidité rappelant le vin et ses saveurs fruitées.',295432730, 'Kenya', 23.70,'Acide', 'Oui'),
(8,'Sumatra Mandheling', 'Café profond et terreux avec un corps lourd et une faible acidité.',302932754, 'Indonésie', 19.95,'Corsé', 'Oui'),
(9,'Costa Rican Tarrazu', 'Café vif et net avec une finition propre et une acidité vive.',327302954, 'Costa Rica', 24.50,'Acide', 'Oui'),
(10,'Vietnamese Robusta', 'Café audacieux et fort avec une saveur robuste distinctive.',549549090, 'Vietnam', 16.75,'Epicé', 'Oui'),
(11,'Tanzanian Peaberry', 'Acidité vive avec un profil de saveur rappelant le vin et un corps moyen.',582954954, 'Tanzanie', 26.80,'Fruité', 'Oui'),
(12,'Jamaican Blue Mountain','Reconnu pour sa saveur douce, son acidité vive et son absence d''amertume.',589100954, 'Jamaique', 39.25,'Doux', 'Oui'),
(13,'Rwandan Bourbon', 'Café avec des notes florales prononcées, une acidité vive et un corps moyen.',650753915, 'Rwanda', 21.90, 'Fruité', 'Oui'),
(14,'Panamanian Geisha', 'Café rare aux arômes floraux complexes, une acidité brillante et un profil de saveur distinctif.',954589100, 'Panama', 42.00,'Fruité', 'Oui'),
(15,'Hawaiian Kona', 'Café rare au goût riche, une acidité douce et des nuances subtiles.',958090105, 'Hawaï', 55.75,'Doux', 'Non'),
(16,'Nicaraguan Maragogipe', 'Café avec des notes de fruits, une acidité vive et un corps plein.',691550753, 'Nicaragua', 28.60,'Fruité', 'Non');